{
 "title": "Resource Panels",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "Prometheus" }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stack",
   "type": "timeseries",
   "description": "Number of bytes allocated on the stack. ",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_stack_sys_bytes{}", "legendFormat": "bytes" }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "description": "Number of bytes allocated on the heap. ",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes{}", "legendFormat": "bytes" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Available on Linux and Windows.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(forwarder_process_cpu_seconds_total{}[$__rate_interval])",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}