---
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version env variables
        run: |
          cat .version >> $GITHUB_ENV

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "${{env.GOLANGCI_LINT_VERSION}}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version env variables
        run: |
          cat .version >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run unit test
        run: make test
